### ISSUE TITLE
patches or fork?

### ISSUE THREAD

**Issue by fwilly** [TobiasNickel/tUploader#6]
I have made local any changes to support folders and for a nicer look. But I don't understand how can I give it to you for review and discussion?

**Comment by TobiasNickel** [comment]
I am also not very experienced with that. I think with an Pull request, I could check out the changes. 

I have already read in your fork and the Support-folder brunch. you had added the a single Filepath to the Querystring of the request and updated the php example so it uses the information. 

That is good, but not what the tUploader is about. I had prefered a solution, that supports the user to drop a folder, that goes through the file-tree uses webkitGetAsEntry, GetAsEntry,  createReader and appends all files to the drop-events file property, proviting the folder information, witch could be send in a standard way to the server, to restore that Filestructure. 

I am glad to see, that you invest time to improve the client app and supporting the dropping of folders is an other task that what I saw now. 

In the end, I like to show you a second small example app, that I made, using the tUploader.js and allmost the same nodeJS server as in this repo. At http://tnickel.de:1111/ is a small app, that let you share photos live with others, that also have this page open. Interesting is, that the Files are manipulated before uplaod. (resized)

**Comment by fwilly** [comment]
> That is good, but not what the tUploader is about. I had prefered a solution, that supports the user to drop a folder, that goes through the file-tree uses webkitGetAsEntry, GetAsEntry, createReader and appends all files to the drop-events file property, proviting the folder information, witch could be send in a standard way to the server, to restore that Filestructure.

This should be possible. The parameter _path_, which will be automatically created by htaccess from given url, is only the current path in which all known operations are executed. If you stay any level down in the folder structure and drop a folder structure there it should be build all folders from there.

> In the end, I like to show you a second small example app, that I made, using the tUploader.js and allmost the same nodeJS server as in this repo. At http://tnickel.de:1111/ is a small app, that let you share photos live with others, that also have this page open. Interesting is, that the Files are manipulated before uplaod. (resized)

Very nice idea and works well. Currently I thinking about, how can I map web users to file system users. We works on any projects to same time. I don't like to use dropbox for. Specially if we are only working internally. But different employees have different rights to see files. The same data structure we use per SSH.
